### ISSUE TITLE
Weakness 

### ISSUE THREAD

**Issue by kizzoknight** [Readek/Pokemon-Stream-Tool#2]
Is there a way to display on the app the pokemon you are currently against weakness

**Comment by Readek** [comment]
I'm not sure what you mean? There's auto enemy support for gen 6.

**Comment by kizzoknight** [comment]
For example 

![PXL_20240928_114214593.jpg](https://github.com/user-attachments/assets/25b4c798-baba-4588-99a1-99a47c7898e5)

Below it's type here it would be good to show the types it's weak against and showing the type and the type weakness on the Vs trainer screen

**Comment by Readek** [comment]
Hmm, I *could* add some sort of `type -> weak to [types]`, but I don't know. I never considered that a purpose of the tool, and I'm sure there are hundreds of other tools out there that can already do this.

But I wouldn't include this info on the trainer VS screen at all. That view is already over saturated with info, and with pokemon types already on screen, most would consider type weaknesses redundant.

**Comment by kizzoknight** [comment]
It would be helpful for me definitely as I can never remember anything this is the closest tool ive found that does what i need
